# roles/mariadb/tasks/firewall.yml
---

- name: check if firewalld is installed
  command: rpm -q firewalld
  args:
    warn: no
  register: rpm_check
  failed_when: "'FAILED' in rpm_check.stderr"

- name: Permit access to Wildfly application port
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  when: rpm_check.stdout != "package firewalld is not installed"

- name: Permit access to Wildfly management port
  firewalld:
    port: 9990/tcp
    permanent: true
    state: enabled
  when: rpm_check.stdout != "package firewalld is not installed"

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: rpm_check.stdout != "package firewalld is not installed"

#- name: disable firewalld
#  systemd:
#    name: firewalld
#    state: stopped
#  when: rpm_check.stdout != "package firewalld is not installed"